### ISSUE TITLE
Wondering what this code does

### ISSUE THREAD

**Issue by tnrich** [IsaacLuo/SnapGeneFileReader#1]
Hey @IsaacLuo 

Thanks for making this repository! I am currently trying to convert it to a javascript repo.

I was wondering what this code did: 

```python
data["dna"] = dict(
                topology="circular" if props & 0x01 else "linear",
                strandedness="double" if props & 0x02 > 0 else "single",
                damMethylated=props & 0x04 > 0,
                dcmMethylated=props & 0x08 > 0,
                ecoKIMethylated=props & 0x10 > 0,
                length=block_size - 1
            )
```

specifically the: `props & 0x01` and `props & 0x04` parts. What is the 0x01 doing?

Thanks!

**Comment by IsaacLuo** [comment]
Hi @tnrich,

Glad to hear you like this repository. Looking forward to see your JavaScript code.
in Snapgene file, there are some bits flags to show the properties of this sequence. These bits are put in a integer to save space.

If the sequence is "circular" and "double strand", the flags will be 0011 in binary, the most right bit is showing this sequence is circular, the 2nd bit from right is showing this sequence is double strand.
use ‘&’ can filter the last bit from the number 
0011 & 0001 == 0001 (true)
0010 & 0000 == 0000 (false)

**Comment by tnrich** [comment]
Thanks for the info @IsaacLuo! I've credited you and this repo in our readme and in the parser file itself  :)

We've made a first pass implementation of the javascript version here: 

https://github.com/TeselaGen/ve-sequence-parsers/#snapgenetojson-dna-files

It curently only has a few simple things it is currently parsing into our generic "Teselagen" json format: https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/test/snapgeneToJson.test.js

Hopefully more can be added as our users require additional details. 

Thanks again @IsaacLuo
